image:
  file: .gitpod.Dockerfile

# List the ports you want to expose and what to do when they are served. See https://www.gitpod.io/docs/config-ports/
ports:
  - port: 4200 # Angular App
    onOpen: open-preview
  - port: 3000 # Backend - Json Server
    onOpen: ignore
    visibility: public

vscode:
  extensions:
    - esbenp.prettier-vscode
    - vscode-icons-team.vscode-icons
    - dbaeumer.vscode-eslint
    - coenraads.bracket-pair-colorizer
    - vscodevim.vim
    - angular.ng-template
    - johnpapa.angular2
    - ms-vscode.vscode-typescript-tslint-plugin
    - wakatime.vscode-wakatime
